sudo: required
services:
  - docker
before_install:
  - docker build -t bmsa/web-client -f ./Dockerfile.dev .
script:
  - docker run -e CI=true bmsa/web-client npm run test
after_success:
  - docker build -t $DOCKER_ID/buymystuffapp-web-client .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push $DOCKER_ID/buymystuffapp-web-client
branches:
  only:
    - master